# Generated by Django 4.0.6 on 2022-07-04 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('tm_date', models.DateField()),
                ('application', models.CharField(max_length=20)),
                ('activity', models.CharField(max_length=20)),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)])),
                ('public_id', models.IntegerField()),
                ('public_comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
